# Generated by Django 6.1.1 on 2026-09-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
